### ISSUE TITLE
fromisoformat() not supported in Python 3.6

### ISSUE THREAD

**Issue by apex2504** [AndyTempel/corona.py#1]
note that in https://github.com/AndyTempel/corona.py#requirements it is stated that python 3.6 is supported. however, https://github.com/AndyTempel/corona.py/blob/master/corona/objects.py#L87 uses `datetime.fromisoformat()` which is not available in py3.6's standard `datetime` lib. `fromisoformat()` was added in py3.7.

**Comment by AndyTempel** [comment]
fixed in b7d998a4b9495b285f93ab702323b6c6511bf2ac
